sudo: required
dist: bionic
language: cpp

install:
  - sudo apt-get install clang-format-6.0
  - sudo apt-get install libboost-all-dev

script:
  - sh scripts/clang_format_test.sh
  - sh scripts/cmake_test.sh 